version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: payflow_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: payflow
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
